# Generated by Django 3.2 on 2021-05-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('car_owner', models.CharField(max_length=100)),
                ('car_notes', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('service_type', models.CharField(blank=True, choices=[('P', 'PLATINUM'), ('G', 'GOLD')], max_length=1)),
                ('submission_date', models.DateTimeField()),
                ('year_old', models.IntegerField(null=True)),
                ('servicing', models.ManyToManyField(blank=True, to='car.service')),
            ],
        ),
    ]
