# Generated by Django 3.2 on 2021-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_notes',
            new_name='car_color',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='service_type',
            field=models.CharField(blank=True, choices=[('PLATINUM', 'PLATINUM'), ('GOLD', 'GOLD')], max_length=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
