# Generated by Django 3.2 on 2021-05-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210506_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='servicing',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='servicing',
            field=models.CharField(blank=True, choices=[('Full-vehicle inspection and correction of any issues', 'Full-vehicle inspection and correction of any issues'), ('Repack wheel bearings', 'Repack wheel bearings'), ('Suspension check', 'Suspension check'), ('Windscreen wiper replacement', 'Windscreen wiper replacement'), ('Wheel alignment', 'Wheel alignment'), ('Transmission service', 'Transmission service'), ('Coolant flush', 'Coolant flush'), ('Brake fluid and brakes check', 'Brake fluid and brakes check'), ('Air-conditioner filter check', 'Air-conditioner filter check'), ('Spark plug replacement', 'Spark plug replacement'), ('Lights check', 'Lights check'), ('Engine check', 'Engine check')], max_length=100),
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
