# Generated by Django 3.2 on 2021-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20210509_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='submission_date',
            field=models.DateTimeField(),
        ),
    ]
